spring:
  application:
    name: feedgramauth

  datasource:
    url: jdbc:postgresql://localhost:5432/feedgram
    username: postgres
    password: tilser

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        feedgramUserChanged:
          destination: feedgram.user.changed
          contentType: application/json


server:
  port: 9000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: davidtilserfeedgramsecrettoken

  service:
    username: d245ef53-5ad5-4216-9c56-89fe0f8302a0
    password: ef919ae4-b893-4969-b782-57978180ad33