spring:
  application:
    name: feedgram-auth

  datasource:
    url: jdbc:postgresql://localhost:5432/feedgram
    username: postgres
    password: tilser

server:
  port: 9000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

security:
  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: davidtilserfeedgramsecrettoken

  service:
    username: d245ef53-5ad5-4216-9c56-89fe0f8302a0
    password: ef919ae4-b893-4969-b782-57978180ad33