spring:
  application:
    name: feedgram-feed

#  data:
#    cassandra:
#      keyspaceName: feedgram_feed
#      contactPoints: localhost
#      port: 9042
#      schema-action: CREATE_IF_NOT_EXISTS

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            key:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
        bindings:
          feedgramUserChanged:
            consumer:
              startOffset: latest
              autoCommitOffset: false
      bindings:
        feedgramUserChanged:
          destination: feedgram.post.changed
          contentType: application/json
          group: feedService
          consumer:
            startOffset: latest
            autoCommitOffset: false

server:
    port: 8003

eureka:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka

security:
  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: davidtilserfeedgramsecrettoken

  service:
    username: d245ef53-5ad5-4216-9c56-89fe0f8302a0
    password: ef919ae4-b893-4969-b782-57978180ad33

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic