spring:
  application:
    name: feedgram-gateway

server:
  port: 8762

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

zuul:
  ignored-services: '*'
  routes:
    feedgram-auth:
      path: /auth/**
      service-id: feedgram-auth
      sensitive-headers: Cookie,Set-Cookie
    feedgram-post:
      path: /post/**
      service-id: feedgram-post
      sensitive-headers: Cookie,Set-Cookie
    feedgram-graph:
      path: /graph/**
      service-id: feedgram-graph
      sensitive-headers: Cookie,Set-Cookie

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 600000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

security:

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: davidtilserfeedgramsecrettoken